name: test-blink
base: core22
version: "0.1"
summary: Blink LED
description: A snap to test WiringPi
architectures:
  - build-on: arm64
  - build-on: amd64

grade: devel
confinement: strict

apps:
  test-blink:
    command: bin/test-blink
    
parts:
  wiring-pi:
    plugin: nil
    override-build: |
      git clone https://github.com/WiringPi/WiringPi.git --depth=1 .
      WIRINGPI_SUDO="" ./build

      mkdir -p $CRAFT_PART_INSTALL/lib
      cp -v /usr/local/lib/libwiringPi.so* $CRAFT_PART_INSTALL/lib/
    build-packages: [git, gcc, g++]

  test-blink:
    after: [wiring-pi]
    plugin: nil
    source: .
    override-build: |
      g++ -Wall -o test-blink test-blink.cpp -lwiringPi
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp test-blink $SNAPCRAFT_PART_INSTALL/bin






